### ISSUE TITLE
Accept negotiator must only take into account media types being used to GET resources

### ISSUE THREAD

**Issue by fortizpenaloza** [ba-st/Stargate#13]
The accept negotiation must only take into account the media types being used to decode objects dropping the ones being used to encode.

**Comment by serpi90** [comment]
When a Specification defines more than one media type, the selector name used to define the mediatype affects the media type resolution, and mediatypes for different verbs on the same endpoints are mixed.
The content negotiation should only use mediatypes for the specified verb and endpoint, not for the whole endpoint.

## Example
If we define the following endpoints:
- GET /pets with `application/vnd.pets+json` defined as `#petsMediaType`
- POST /pets with `application/vnd.pet+json` defined as `#petMediaType`
A request with GET /pets with `*/*` fails because it attempts to respond with `application/vnd.pet+json`, because the Specification has 2 mediatypes, sorted by selector name order and uses the first one.
The problem is that `application/vnd.pet+json` is not valid for GET, it's defined for POST.
